name: Build and Package Qt Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2' # 选择你需要的Qt版本
        host: 'linux'
        target: 'desktop'
        arch: 'gcc_64'

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential devscripts debhelper qtbase5-dev libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev

    - name: Build the project
      run: |
        cd src
        qmake
        make

    - name: Set up debian package directory
      run: |
        mkdir -p debian
        echo "9" > debian/compat
        cat << EOF > debian/control
        Source: teapotrendering
        Section: utils
        Priority: optional
        Maintainer: Blank-Luo <blankluo@foxmail.com>
        Build-Depends: debhelper (>= 9), pkg-config, dpkg-dev, qt5-qmake, qtbase5-dev, qttools5-dev-tools
        Standards-Version: 3.9.6
        Homepage: teapotrendering
        
        Package: teapotrendering
        Architecture: any
        Depends: ${shlibs:Depends}, ${misc:Depends}
        Recommends: libqt5libqgtk2, kimageformat-plugins
        Description: A Qt application for rendering a teapot using OpenGL A simple Qt application that uses OpenGL to render a teapot.
        EOF

        cat << EOF > debian/changelog
        teapotrendering (1.0.1) unstable; urgency=low

          * Initial release.

         -- Blank-Luo <blankluo@foxmail.com>  $(date -R)
        EOF

        cat << EOF > debian/rules
        #!/usr/bin/make -f
        include /usr/share/dpkg/default.mk
        export QT_SELECT = qt5
        %: 
        	dh $@ --parallel
        override_dh_auto_configure:
        	dh_auto_configure -- DEFINES+="VERSION=$(DEB_VERSION_UPSTREAM)"
        EOF

        chmod +x debian/rules

    - name: Build Debian package
      run: |
        dpkg-buildpackage -b -us -uc

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: debian-packages
        path: |
          ../*.deb
          ../*.changes
          ../*.build
